# Site settings
title: Vahe Taamazyan - 3D Computer Vision Researcher
email: vaheta@gmail.com
description: Senior Research Scientist in 3D Computer Vision for Robotics
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://vaheta.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
permalink: /blog/:title/

# Collections
collections:
  posts:
    output: true
    permalink: /blog/:title/

# Defaults
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
